name: Release Go Binary

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          cache: true

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pkg-config \
            libwayland-dev \
            libx11-dev \
            libx11-xcb-dev \
            libxkbcommon-dev \
            libxkbcommon-x11-dev \
            libgles2-mesa-dev \
            libegl1-mesa-dev \
            libffi-dev \
            libxcursor-dev \
            libvulkan-dev

      - name: Build all versions
        run: make all

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/*